name: Update data.json

on:
  repository_dispatch:
    types: [update-data]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update data.json
        run: |
          echo "$DATA_JSON" > data.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json || echo "nothing to add"
          git commit -m "Update data.json via dispatch" || echo "nothing to commit"
          git push origin HEAD:main
        env:
          DATA_JSON: ${{ github.event.client_payload.json }}
