name: تحديث data.json

on:
  repository_dispatch:
    types: [update_data]

jobs:
  update-data-json:
    runs-on: ubuntu-latest
    steps:
    - name: استنساخ المستودع
      uses: actions/checkout@v3

    - name: تحديث ملف data.json
      run: |
        echo "${{ github.event.client_payload.new_data }}" > data.json
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add data.json
        git commit -m "تحديث data.json بواسطة GitHub Actions"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
